# frozen_string_literal: true

# Load the Rails application.
require_relative 'application'

# Initialize the Rails application.
Rails.application.initialize!

PUBLISHABLE_KEY="pk_test_51JZWMuEVSKB0mGfOY5sTEpVGMlvmxq6LuOkWzaGZEzrDTkCatKblEo4ZogeVlR5S5iHku4USfSgMn3jw7Tmi4Kl700dUvrravD"
SECRET_KEY="sk_test_51JZWMuEVSKB0mGfOILroTaaY9Vu5wmtfxxSEAIqkzt65XvhhILv7ebRCW41VJxm4yL2lzbJiy5KBH3NpaGc7T1fX00DDmXFSy0"
